---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rabbitmq-cr
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-sa
  namespace: services
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{APP_NAME}}-crb
roleRef:
  kind: ClusterRole
  name: services-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rabbitmq-sa
  namespace: services
